version: '3'

services:
  db-postgres-pokedex:
    image: postgres:alpine
    ports:
      - "2345:5432"
    container_name: "db-postgres-pokedex"
    restart: always
    volumes:
      - ./volume-docker:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

volumes:
  volume-docker: